### ISSUE TITLE
data.Y, data.comp1, data.comp2: Request example files  .csv or .txt

### ISSUE THREAD

**Issue by AnnaPrivi** [wwylab/DeMixTallmaterials#1]
Hello to all wwylab group, 

First congratulations on the useful package. I'd like to test DemixT on Rnaseq data normalized with edgeR package. I'm having some confusion about formatting input data => data.Y, data.comp1, data.comp2. 
Is it possible to request an example in .csv or .txt for each of these input files? 
- data.Y is the matrix GxS with normalized data of mixed tumor samples, right?
- data.comp1 is the matrix GxS of normalized Normal samples, right? 
- data.comp2   is it still reference?   additional reference samples? some examples?

- do i need to specify which are the normal sample and which are the tumor samples in the matrix with a string like the following example: **design <- c(rep(0,50), rep(1,151)**?
I apologize for this basic issue,  I am getting confusion between the different versions of the package and the SummarizedExperiment object. 
Thank you a lot for your time

Best Regards

**Comment by ShaolongCao** [comment]
Thank you for your comments. 
data.Y is the mixed expression; data.comp1 is the normal expression. If you are not using three component deconvolution, you can just leave the data.comp2 as Null (which is the default input).

The DeMixTallmaterials is the historical archive version. Here is the link to the latest version: https://github.com/wwylab/DeMixT

**Comment by AnnaPrivi** [comment]
Hi ShaolongCao, 

thank you to answer me. 
I have solved the problem i had by myself. 
I just have another question, i would like to use the three component analysis. 
So i perfomed the deconvolution of data.Y = tumor sample and comp1= normal sample (updated version of the package).
I used the DeMixT function and then created this file excel to show you the results of just an example.
I suppose that the pi1 is the propotion of the stroma component?
[Res_DeMixT_test.xlsx](https://github.com/wwylab/DeMixTallmaterials/files/3252949/Res_DeMixT_test.xlsx)

Now i would like to use this result to calculate the third component (immune component). So i would like to ask you some suggestions to calculate the third component and which values (from the first results) should i considerate to perform the three component deconvolution? 

I am following this code for the TCGA samples https://bioinformatics.mdanderson.org/Software/DeMixT/online_methods.html#TCGA%20HNSCC%20data
Unfortunately, The code there is for the early version. 

I look foward to hearing from you. 
Thank you for your time.

**Comment by ShaolongCao** [comment]
1. Yes. pi1 is the proportion of the stroma component.
2. If you want to calculate the third component (immune), you need to select high immune-infiltrated samples as the reference. You can find the description of our newly developed tumor-immune-stroma deconvolution pipeline in our BioRxiv paper. https://www.biorxiv.org/content/biorxiv/early/2019/03/05/566075.full-text.pdf

Let me know if you have any questions.

**Comment by AnnaPrivi** [comment]
Hi ShaolongCao, 

thank you to answer me. 
I have read the suggested documentation. 
So let´s me explain if i have understood correctly. 
There are three steps: 

1) I run function "demixt " with two components giving:
              data.Y = only tumor mixed sample (from TGCA repositories after normalization)
              comp1 = normal sample ( the normal sample from TGCA repositories after normalization)

RESULTS: from this i get the "exprT" => deconvoluted expression of the tumor without stroma       component. I will use this tab as input for the next step. I will call this result **Tumor_1**
In the documentation what do you excatly mean with " (e.g., DeMixT 2-component proportion > 85%)"  do i need to apply some filter in the given results?

2) i run demixt with two component giving

              data.Y = **Tumor_1** (the result from before) Tumor component withour stroma component 
              comp1 = selected dataset (from other experiment) known to be with high immune infiltration (from TCGA repositories)

RESULTS: from this i get the "exprN" => deconvoluted expression of the reference without tumor component. i will call this result **"immune_1"**

3) i run demixt with three component analysis giving:
        data.Y= all mixed tumor from TGCA
        comp1= normal samples from TGCA
        comp2 = Immune_1 calculated from the previous two steps. 

is that correct? Could i kindly you ask you if you could give me an exhaustive answer steps by steps with the precise results should i take from each steps? 
Could i use as reference for TGCA RNA-seq data tumor mixed samples, some other normalized experiment (microarrays profile) that i know to be high in immune component? 

Thank you for your time.

**Comment by ShaolongCao** [comment]
1. (DeMixT 2-component proportion > 85%) means you need to build new **Tumor_1** matrix using samples with >85% tumor purity.

2. In the second step, the key point is to select high immune infiltrated samples (those samples are not the same samples in step 1). Then let comp1=normal, comp2=**Tumor_1** and data.Y=(mixed expression of high immune infiltrated samples). By doing this, you can get exprT as the deconvolved immune component of **immune_1**.

3. Your understanding is correct.

We don't have experience using TCGA and other data together. There will be potential batch effect issue that you need to adjust before you merge two RNAseq databased together.

If you can give me an email address, I can share our current code of 3-component deconvolution pipeline. My email is scao@mdanderson.org.
