### ISSUE TITLE
Running into problem when analyze TCGA liver cancer data

### ISSUE THREAD

**Issue by thestarocean** [wwylab/DeMixTallmaterials#3]
I was using  DeMixT (version 0.2) to perform Transcriptome Deconvolution for TCGA data. I used TCGA paired normal tissues as references and selected 10 tumor tissue samples with high StromalScore and low ImmuneScore identified by Estimate algorithm to perform 2-component analysis. However, the algorithm stopped with when running step2 with Error message:

Error in if (sum(obj == 0) > 1) { : missing value where TRUE/FALSE needed

And Printing rres[22] from Optimum.KernelC.R at lines 62 says it's NaN.
So what could be the cause of this problem? Is there a solution to fix it?

**Comment by ShaolongCao** [comment]
That's odd, we did perform analysis of TCGA LIHC read counts data which worked well. Did you do any transformation/normalization before input to the DeMixT model? We usually perform scale or quantile normalization for the input data (raw read counts), before running the model.

By the way, we are releasing a new version of DeMixT very soon, probably in this week or next week. Will keep you update. The latest version will be released at https://github.com/wwylab/DeMixT

Best,
Shaolong

**Comment by thestarocean** [comment]
Thank you. I was using fpkm and remove any gene with zero value. I will give raw count a try and do the  quantile normalization to see if it could went smothly. And I look forward for the next version of DeMixT!

**Comment by ShaolongCao** [comment]
The updated package is available now on Github: https://github.com/wwylab/DeMixT
Please try the new one.

Best,
Shaolong
