### ISSUE TITLE
Error after finishing iterations

### ISSUE THREAD

**Issue by Emberwhirl** [wwylab/DeMixTallmaterials#4]
Hi. I recently used the tool for deconvolution of RNAseq and microarray experiments. I have tried to run this tool both on Windows and Ubuntu, and came across the same error "Error in if (sum(obj == 0) > 1) { : missing value where TRUE/FALSE needed" when the iterations were finished.

**Comment by pengyang0411** [comment]
Hi,

Thank you for being interested in our work.
We have not seen this error before. Can you provide me with the input data and the commands you used? We will debug on our side. My email address is pyang7@mdanderson.org.

Thanks,
Peng
